name: CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
jobs:
    integration-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.9'
            - name: Install Docker Compose
              run: |
                  sudo apt-get update
                  sudo apt-get install docker-compose -y
            - name: Start LocalStack with Docker Compose
              run: docker-compose up -d
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            
            - name: Set PYTHONPATH
              run: |
                  echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
                  echo "Current directory: $(pwd)"
                  ls -la
                  
            - name: Run pylint
              run: |
                  pylint --fail-under 7 app
                  exitcode="$?"
                  echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
                  exit "$exitcode"
                  
            - name: Run unit tests
              run: |
                  pytest tests/test_unit.py -v
                  
            - name: Run BDD tests
              run: |
                  behave tests/features
                  
            - name: Run integration tests
              run: |
                  pytest tests/test_integration.py -v
                  coverage run -m pytest && coverage report -m
                  
            - name: Teardown Docker
              if: always()
              run: docker-compose down 